name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm dlx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
